var countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Angola',
  'Armenia',
  'Australia',
  'Azerbaijan',
  'Bangladesh',
  'Barbados',
  'Belgium',
  'Benin',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Brazil',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Canada',
  'Central African Republic',
  'Chad',
  'China',
  'Colombia',
  'Côte d’Ivoire',
  'Cuba',
  'Democratic Republic of Congo',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Ethiopia',
  'Fiji',
  'France',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Guinea-Bissau',
  'Haiti',
  'Honduras',
  'India',
  'Indonesia',
  'Iraq',
  'Ireland',
  'Italy',
  'Japan',
  'Jordan',
  'Kenya',
  'Laos',
  'Lebanon',
  'Liberia',
  'Malawi',
  'Malaysia',
  'Mali',
  'Mauritania',
  'Mexico',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'Occupied Palestinian',
  'Territory',
  'Pakistan',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Russian Federation',
  'Rwanda',
  'Senegal',
  'Sierra Leone',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste (East Timor)',
  'Tunisia',
  'Turkey',
  'Uganda',
  'United Kingdom',
  'United States of America',
  'Vanuatu',
  'Vietnam',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]


var affilates = [
  'Oxfam America',
  'Oxfam Australia',
  'Oxfam-in-Belgium',
  'Oxfam Brazil',
  'Oxfam Canada',
  'Oxfam IBIS (Denmark)',
  'Oxfam France',
  'Oxfam Germany',
  'Oxfam Great Britain',
  'Oxfam Hong Kong',
  'Oxfam India',
  'Oxfam Ireland',
  'Oxfam Italy',
  'Oxfam Japan',
  'Oxfam Mexico',
  'Oxfam Novib (Netherlands)',
  'Oxfam New Zealand',
  'Oxfam-Québec',
  'Oxfam Intermón (Spain)',
  'Oxfam South Africa',
]